### ISSUE TITLE
Review: Landing and VolunteerCollection

### ISSUE THREAD

**Issue by marissahalim** [aloha-time/aloha-time#19]
For this review, we're going to review the Landing page and the Volunteer collection.

**Review Branch**
---
review-19

**Files to be Reviewed**
---
- [Landing.jsx](https://github.com/aloha-time/aloha-time/blob/issue-2/app/imports/ui/pages/Landing.jsx)
- [VolunteerCollection.js](https://github.com/aloha-time/aloha-time/blob/issue-12/app/imports/api/user/VolunteerCollection.js)

**Checklists**
---
- [Architecture](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-architecture-checklist)
- [JS & ESL](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-ui-checklist)

**Specific requests for this review**
---
n/a

**Due Date**
---
12pm, Tuesday, February 1st

**Documentation**
---
The review process is documented at: [https://www.radgrad.org/docs/developers/reviews/overview](https://www.radgrad.org/docs/developers/reviews/overview)

**Comment by rainllo** [comment]
Landing.jsx - ES-01: Missing required 'alt' attribute , line 11

**Comment by marissahalim** [comment]
Landing:
UI-02: The page content gets cut off when viewed on mobile screens

**Comment by hanseca** [comment]
Landing page file:
L11: ES-01: ESLint warning about missing alt attribute for an img tag as well as not resolving direcory for images and file for the logo

L25, 26: ES-01: ESLint warning about a tag having an empty body

**Comment by rainllo** [comment]
Landing.jsx - UI-07: Warning: Received `true` for a non-boolean attribute `fluid`.

**Comment by jon-valencia** [comment]
Landing.jsx
RE-03: Rename “export const VolunteerProfiles = new VolunteerCollection();” to “export const Volunteer = new VolunteerCollection();” maybe???

**Comment by FeimeiChen** [comment]
Landing.jsx- needs a meaning className such as header maybe should be landing-page-header.

**Comment by chadoshiro** [comment]
Landing: 
AR-02 - Put images in the correct directory.
ES-01 - Warnings for different issues in the file.
UI-02 - The screen for the mobile device is messed up. Fix it to make it look better on a mobile device.

**Comment by marissahalim** [comment]
**Outcome of review**
---
New Issues:
-Update Organization & Volunteer Collections
-Update page responsiveness for mobile

Other Issues:
- Organize images for landing page

**Comment by cammoore** [comment]
## Landing.jsx

L9: Why is the PAGE_ID associated with the Grid and not the first div?

Why all the divs?

DE-07: L33-36, etc: These should be components we import and
instantiate. Eventually the information will come from a collection.

## VolunteerCollection.js

L9: We don't add any additional information about volunteers to the
base profile?
L24: Shouldn't the role be ROLE.VOLUNTEER?
L72: Update the set of roles.
L84: Update the role.

**Comment by quinnbl** [comment]
Landing.jsx:
UI-02: Doesn't work well on mobile, cutoff and shrinking of icons.
VolunteerCollection.js:
ES-01: Unresolved variable User , line 84
ES-01: Returned expression type {firstName: any, lastName: any, email: any} is not assignable to type never , line 101
