### ISSUE TITLE
Review: NavBar and OrgItem

### ISSUE THREAD

**Issue by chadoshiro** [aloha-time/aloha-time#49]
For this review, we're going to review the NavBar component and the OrgItem component.

**Review Branch**
---
review-49

**Files to be Reviewed**
---
- [NavBar.jsx](https://github.com/aloha-time/aloha-time/blob/issue-14/app/imports/ui/components/NavBar.jsx)
- [OrgItem.jsx](https://github.com/aloha-time/aloha-time/blob/issue-10/app/imports/ui/components/OrgItem.jsx)

**Checklists**
---
- [Architecture](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-architecture-checklist)
- [JS & ESL](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-ui-checklist)

**Specific requests for this review**
---
n/a

**Due Date**
---
12pm, Tuesday, February 8th

**Documentation**
---
The review process is documented at: [https://www.radgrad.org/docs/developers/reviews/overview](https://www.radgrad.org/docs/developers/reviews/overview)

**Comment by FeimeiChen** [comment]
NavBar.jsx: please give ride of the white space below the NavBar by changing the const menuStyle = { marginBottom: '30px' }; to smaller value such 10px

**Comment by jon-valencia** [comment]
NavBar.jsx: I think we should consider making things like the organization library available to everyone even if they're not signed in.

**Comment by marissahalim** [comment]
OrgItem
- still references stuff
NavBar
- needs to be updated with functions for Volunteer, Organization, and Admin
- layout for mobile needs to be fixed

**Comment by cammoore** [comment]
## NavBar.jsx

L7,8 Remove the commented-out lines or use the role.
L19: Change the route.


## OrgItem.jsx

L6: Remove reference to Stuff.
L7: Pass in the organization.
L21: No stuff define the organization structure.
L30: Also add withTracker so you can pass in the organization.

**Comment by rainllo** [comment]
OrgItem.jsx:
UI-07: The console reveals the following errors:
  - Warning: Failed prop type: The prop 'stuff' is marked as required in 'OrgItem', but its value is 'undefined'.
  - Warning: Failed prop type: The prop 'stuff' is marked as required in 'OrgItem2', but its value is 'undefined'.

**Comment by chadoshiro** [comment]
NavBar:
ES-01: There are warnings and typos that can be addressed

Also, there are comments that are for imports that can be removed until we need it

OrgItem:
UI-02: Make it look nicer when on a mobile screen

JS-07: Remove JS doc comment

**Comment by rainllo** [comment]
NavBar.jsx:
UI-01: A "Browse Opportunities" search bar and a "Browse Opportunities" in the dropdown seems redundant.
UI-03: The "Organization Library" seems like an important page, but is hidden in a dropdown. Consider moving it to the first level users need to do less clicking.

**Comment by hanseca** [comment]
OrgItem.jsx file:
L13: AR-01: Directories should use lowercase with - between words. It is currently "/orginfo".

**Comment by quinnbl** [comment]
Navbar:

ES-01 - Typos and warnings exist
UI-01 - Making organizations available to non-users would make thigs more obvious
