### ISSUE TITLE
Review: ListOpportunity and MyOrganizationProfile

### ISSUE THREAD

**Issue by rainllo** [aloha-time/aloha-time#52]
For this review, we're going to review the x and y.

**Review Branch**
---
review-52

**Files to be Reviewed**
---
- [ListOpportunity.jsx](https://github.com/aloha-time/aloha-time/blob/main/app/imports/ui/pages/ListOpportunity.jsx)
- [MyOrganizationProfile.jsx](https://github.com/aloha-time/aloha-time/blob/main/app/imports/ui/pages/MyOrganizationProfile.jsx)

**Checklists**
---
- [Architecture](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-architecture-checklist)
- [JS & ESL](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-ui-checklist)

**Specific requests for this review**
---
n/a

**Due Date**
---
12pm, Tuesday, February 15th

**Documentation**
---
The review process is documented at: [https://www.radgrad.org/docs/developers/reviews/overview](https://www.radgrad.org/docs/developers/reviews/overview)

**Comment by rainllo** [comment]
MyOrganizationProfile.jsx:
ES-01: Line 120 - Unresolved function or method subscribe()

**Comment by rainllo** [comment]
ListOpportunity.jsx:
RE-06: List of opportunities is only rendered when logged in as john@foo.com, but not as other users.

**Comment by FeimeiChen** [comment]
We need as organization role to login to see organization their own profile, if you login as volunteer, you can not see organization's  profile because you are volunteer, so we need add OrganizationProtectedRout for organization relate files

**Comment by cammoore** [comment]
## ListOpportunity.jsx

L11: Prefer pure functional components over classes.
L31: map function's first parameter, opportunities, is poorly named.
L32: Shouldn't use index for the key. You can use opportunity._id.

## MyOrganizationProfile.jsx

L10: Stuff!
L11: is 'doc' the right name?
L19: Should image src be a property of OrganizationProfile?
Think about the properties you need to show.

**Comment by jon-valencia** [comment]
ListOpportunity.jsx: Not a big issue now, but in the future we should look to integrate the opportunity collection to the organization role

MyOrganizationProfile.jsx:
I kinda fixed the problem with not being able to see the organization profile w/OrgInfo.jsx

**Comment by marissahalim** [comment]
MyOrganizationProfile
- change the comment that references Stuff to something relevant to the file
- change doc to something like orgProfile

**Comment by chadoshiro** [comment]
MyOrganizationProfile.jsx
- There is a reference to Stuff and StuffCollection in the comments.

**Comment by hanseca** [comment]
MyOrganizationProfile.jsx

RE-01: Try simplifying and breaking into subcomponents/
